app:
  name: 'go-loyalty-system'
  version: '1.0.0'

http:
  port: '8080'
  address: ':8080'

logger:
  log_level: 'debug'
  rollbar_env: 'go-loyalty-system'


postgres:
  pool_max: 10
  
accrual:
  address: ':8081' 

