version: '3'

services:
  accrual:
    build:
      context: .
      dockerfile: Dockerfile.accrual
    image: ubuntu:20.04
    container_name: accrual
    volumes:
      - .:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    command: ./cmd/accrual/accrual_linux_amd64 -a=:8081
    environment:
      - ACCRUAL_PORT=8081
      - ACCRUAL_HOST=0.0.0.0
      - ACCRUAL_SYSTEM_ADDRESS=:8081
      - DATABASE_URI=postgresql://${DB_USER:-admin}:${DB_PASSWORD:-admin}@loyalty_db:5432/${DB_NAME:-admin}?sslmode=disable
    ports:
      - "8081:8081"
    networks:
      - loyalty_network

networks:
  loyalty_network:
    name: loyalty_network
    external: true