version: '3'

services:
  loyalty_db:
    image: postgres:15-alpine
    container_name: loyalty_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-admin}
      POSTGRES_USER: ${POSTGRES_DB:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_DB:-admin}
    ports:
      - "5430:5432"
    networks:
      - loyalty_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-admin}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  loyalty_network:
    name: loyalty_network
    external: true

volumes:
  postgres_data: