
services:
  market:
    image: golang:1.22-alpine
    container_name: market
    volumes:
      - .:/go/src/go-with-compose
      - ./migrations:/app/migrations
    working_dir: /go/src/go-with-compose
    command: go run cmd/gophermart/main.go
    depends_on:
      - loyalty_db
    environment:
      - DATABASE_URI=postgresql://${DB_USER:-admin}:${DB_PASSWORD:-admin}@loyalty_db:5432/${DB_NAME:-admin}?sslmode=disable
      - ACCRUAL_SYSTEM_ADDRESS=http://accrual:8081
    ports:
      - "8080:8080"
    networks:
      - loyalty_network

  accrual:
    image: ubuntu:20.04
    container_name: accrual
    volumes:
      - .:/go/src/go-with-compose
    working_dir: /go/src/go-with-compose
    command: ./cmd/accrual/accrual_linux_amd64 -a=:8081
    environment:
      - ACCRUAL_PORT=8081
      - ACCRUAL_HOST=0.0.0.0
      - ACCRUAL_SYSTEM_ADDRESS=:8081
      - DATABASE_URI=postgresql://${DB_USER:-admin}:${DB_PASSWORD:-admin}@loyalty_db:5432/${DB_NAME:-admin}?sslmode=disable
    ports:
      - "8081:8081"
    networks:
      - loyalty_network
    
  loyalty_db:
    image: postgres:15-alpine
    container_name: loyalty_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-admin}
      POSTGRES_USER: ${POSTGRES_DB:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_DB:-admin}
    ports:
      - "5430:5432"
    networks:
      - loyalty_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-admin} -d ${DB_NAME:-admin}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  loyalty_network:
    driver: bridge