version: '3'

tasks:
  install-linter:
    desc: Install golangci-lint based on the GOOS value from go env
    cmds:
      - |
        GOOS=$(go env GOOS)
        case "$GOOS" in
          "windows")
            if command -v choco > /dev/null; then
              echo "Installing golangci-lint with Chocolatey..."
              choco install golangci-lint
              exit 0
            else
              echo "Error: Chocolatey is not installed. Please install it first: https://chocolatey.org/install"
              exit 1
            fi
            ;;
          "darwin")
            if command -v brew > /dev/null; then
              echo "Installing golangci-lint with Homebrew..."
              brew install golangci-lint
              exit 0
            else
              echo "Error: Homebrew is not installed. Please install it first: https://brew.sh/"
              exit 1
            fi
            ;;
          "linux")
            if [ -f /etc/os-release ]; then
              . /etc/os-release
              if [ "$ID" = "ubuntu" ]; then
                echo "Ubuntu detected. Installing golangci-lint using snap..."
                sudo snap install golangci-lint --classic
                exit 0
              else
                echo "Linux detected, but not Ubuntu. Please install golangci-lint using your package manager."
                echo "Examples:"
                echo "  apt: sudo apt install golangci-lint"
                echo "  yum: sudo yum install golangci-lint"
                echo "  pacman: sudo pacman -S golangci-lint"
                exit 0
              fi
            else
              echo "Linux detected, but OS information could not be determined."
              echo "Please install golangci-lint using your package manager."
              exit 0
            fi
            exit 1
            ;;
          *)
            echo "Unsupported OS: $GOOS"
            exit 1
            ;;
        esac

  lint:
    desc: Run linters using golangci-lint
    cmds:
      - golangci-lint run --config .golangci.yml

  clear:
    desc: Clear temporary files and directories
    cmds:
      - mkdir -p ./.runtime
      - rm -f ./logs/{test1.log}

  build:
    desc: Build the project
    deps: [lint, clear]
    cmds:
      - go fmt ./...
      - go vet ./...
      - go build -o ./.runtime/gophermart.exe cmd/gophermart/main.go

  test:
    desc: Run tests
    deps: [build] 
    cmds:
      - gophermarttest -test.v  -test.run=^TestGophermart$ -gophermart-binary-path=./.runtime/gophermart.exe -gophermart-host=localhost -gophermart-port=8080 -gophermart-database-uri="postgres://postgres:admin@localhost:5432/MetricStore?sslmode=disable" -accrual-binary-path=./cmd/accrual/accrual_windows_amd64.exe -accrual-host=localhost -accrual-port=8081 -accrual-database-uri="postgres://postgres:admin@localhost:5432/MetricStore?sslmode=disable" >> logs/test1.log
 







