// Code generated by MockGen. DO NOT EDIT.
// Source: C:\golang\yandex\go-loyalty-system\internal\usecase\interfaces.go

// Package mock_usecase is a generated GoMock package.
package usecase

import (
	context "context"
	entity "go-loyalty-system/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	pgconn "github.com/jackc/pgconn"
	v5 "github.com/jackc/pgx/v5"
)

// MockGopherMartRepo is a mock of GopherMartRepo interface.
type MockGopherMartRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGopherMartRepoMockRecorder
}

// MockGopherMartRepoMockRecorder is the mock recorder for MockGopherMartRepo.
type MockGopherMartRepoMockRecorder struct {
	mock *MockGopherMartRepo
}

// NewMockGopherMartRepo creates a new mock instance.
func NewMockGopherMartRepo(ctrl *gomock.Controller) *MockGopherMartRepo {
	mock := &MockGopherMartRepo{ctrl: ctrl}
	mock.recorder = &MockGopherMartRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGopherMartRepo) EXPECT() *MockGopherMartRepoMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockGopherMartRepo) BeginTx(ctx context.Context) (v5.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(v5.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockGopherMartRepoMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockGopherMartRepo)(nil).BeginTx), ctx)
}

// CheckOrderExistence mocks base method.
func (m *MockGopherMartRepo) CheckOrderExistence(ctx context.Context, orderNumber string, userID uint) (bool, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOrderExistence", ctx, orderNumber, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckOrderExistence indicates an expected call of CheckOrderExistence.
func (mr *MockGopherMartRepoMockRecorder) CheckOrderExistence(ctx, orderNumber, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOrderExistence", reflect.TypeOf((*MockGopherMartRepo)(nil).CheckOrderExistence), ctx, orderNumber, userID)
}

// CreateToken mocks base method.
func (m *MockGopherMartRepo) CreateToken(ctx context.Context, u *entity.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockGopherMartRepoMockRecorder) CreateToken(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockGopherMartRepo)(nil).CreateToken), ctx, u)
}

// CreateWithdrawalTx mocks base method.
func (m *MockGopherMartRepo) CreateWithdrawalTx(ctx context.Context, withdrawal entity.Withdrawal, order *entity.OrderResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawalTx", ctx, withdrawal, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawalTx indicates an expected call of CreateWithdrawalTx.
func (mr *MockGopherMartRepoMockRecorder) CreateWithdrawalTx(ctx, withdrawal, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawalTx", reflect.TypeOf((*MockGopherMartRepo)(nil).CreateWithdrawalTx), ctx, withdrawal, order)
}

// ExistOrderAccrual mocks base method.
func (m *MockGopherMartRepo) ExistOrderAccrual(ctx context.Context, orderNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistOrderAccrual", ctx, orderNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistOrderAccrual indicates an expected call of ExistOrderAccrual.
func (mr *MockGopherMartRepoMockRecorder) ExistOrderAccrual(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistOrderAccrual", reflect.TypeOf((*MockGopherMartRepo)(nil).ExistOrderAccrual), ctx, orderNumber)
}

// GetBalance mocks base method.
func (m *MockGopherMartRepo) GetBalance(ctx context.Context, userID string) (*entity.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(*entity.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockGopherMartRepoMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockGopherMartRepo)(nil).GetBalance), ctx, userID)
}

// GetBalanceTx mocks base method.
func (m *MockGopherMartRepo) GetBalanceTx(ctx context.Context, tx v5.Tx, userID uint) (*entity.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceTx", ctx, tx, userID)
	ret0, _ := ret[0].(*entity.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceTx indicates an expected call of GetBalanceTx.
func (mr *MockGopherMartRepoMockRecorder) GetBalanceTx(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceTx", reflect.TypeOf((*MockGopherMartRepo)(nil).GetBalanceTx), ctx, tx, userID)
}

// GetOrderByNumber mocks base method.
func (m *MockGopherMartRepo) GetOrderByNumber(ctx context.Context, orderNumber string) (*entity.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", ctx, orderNumber)
	ret0, _ := ret[0].(*entity.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockGopherMartRepoMockRecorder) GetOrderByNumber(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockGopherMartRepo)(nil).GetOrderByNumber), ctx, orderNumber)
}

// GetUnprocessedOrders mocks base method.
func (m *MockGopherMartRepo) GetUnprocessedOrders(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessedOrders", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessedOrders indicates an expected call of GetUnprocessedOrders.
func (mr *MockGopherMartRepoMockRecorder) GetUnprocessedOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessedOrders", reflect.TypeOf((*MockGopherMartRepo)(nil).GetUnprocessedOrders), ctx)
}

// GetUserByEmail mocks base method.
func (m *MockGopherMartRepo) GetUserByEmail(ctx context.Context, u entity.User) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, u)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockGopherMartRepoMockRecorder) GetUserByEmail(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockGopherMartRepo)(nil).GetUserByEmail), ctx, u)
}

// GetUserByLogin mocks base method.
func (m *MockGopherMartRepo) GetUserByLogin(ctx context.Context, u entity.User) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, u)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockGopherMartRepoMockRecorder) GetUserByLogin(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockGopherMartRepo)(nil).GetUserByLogin), ctx, u)
}

// GetUserOrders mocks base method.
func (m *MockGopherMartRepo) GetUserOrders(ctx context.Context, userID uint) ([]entity.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", ctx, userID)
	ret0, _ := ret[0].([]entity.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockGopherMartRepoMockRecorder) GetUserOrders(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockGopherMartRepo)(nil).GetUserOrders), ctx, userID)
}

// GetUsers mocks base method.
func (m *MockGopherMartRepo) GetUsers(arg0 context.Context) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", arg0)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockGopherMartRepoMockRecorder) GetUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockGopherMartRepo)(nil).GetUsers), arg0)
}

// GetWithdrawals mocks base method.
func (m *MockGopherMartRepo) GetWithdrawals(ctx context.Context, userID uint) ([]entity.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]entity.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockGopherMartRepoMockRecorder) GetWithdrawals(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockGopherMartRepo)(nil).GetWithdrawals), ctx, userID)
}

// RegisterUser mocks base method.
func (m *MockGopherMartRepo) RegisterUser(ctx context.Context, u entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockGopherMartRepoMockRecorder) RegisterUser(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockGopherMartRepo)(nil).RegisterUser), ctx, u)
}

// SaveAccrual mocks base method.
func (m *MockGopherMartRepo) SaveAccrual(ctx context.Context, orderNumber, status string, accrual float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAccrual", ctx, orderNumber, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAccrual indicates an expected call of SaveAccrual.
func (mr *MockGopherMartRepoMockRecorder) SaveAccrual(ctx, orderNumber, status, accrual interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAccrual", reflect.TypeOf((*MockGopherMartRepo)(nil).SaveAccrual), ctx, orderNumber, status, accrual)
}

// SetOrders mocks base method.
func (m *MockGopherMartRepo) SetOrders(ctx context.Context, userID uint, order entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrders", ctx, userID, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOrders indicates an expected call of SetOrders.
func (mr *MockGopherMartRepoMockRecorder) SetOrders(ctx, userID, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrders", reflect.TypeOf((*MockGopherMartRepo)(nil).SetOrders), ctx, userID, order)
}

// UpdateBalanceTx mocks base method.
func (m *MockGopherMartRepo) UpdateBalanceTx(ctx context.Context, tx v5.Tx, userID uint, amount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalanceTx", ctx, tx, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalanceTx indicates an expected call of UpdateBalanceTx.
func (mr *MockGopherMartRepoMockRecorder) UpdateBalanceTx(ctx, tx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalanceTx", reflect.TypeOf((*MockGopherMartRepo)(nil).UpdateBalanceTx), ctx, tx, userID, amount)
}

// ValidateOrder mocks base method.
func (m *MockGopherMartRepo) ValidateOrder(order entity.Order, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateOrder", order, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateOrder indicates an expected call of ValidateOrder.
func (mr *MockGopherMartRepoMockRecorder) ValidateOrder(order, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateOrder", reflect.TypeOf((*MockGopherMartRepo)(nil).ValidateOrder), order, userID)
}

// MockOrderUseCase is a mock of OrderUseCase interface.
type MockOrderUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockOrderUseCaseMockRecorder
}

// MockOrderUseCaseMockRecorder is the mock recorder for MockOrderUseCase.
type MockOrderUseCaseMockRecorder struct {
	mock *MockOrderUseCase
}

// NewMockOrderUseCase creates a new mock instance.
func NewMockOrderUseCase(ctrl *gomock.Controller) *MockOrderUseCase {
	mock := &MockOrderUseCase{ctrl: ctrl}
	mock.recorder = &MockOrderUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderUseCase) EXPECT() *MockOrderUseCaseMockRecorder {
	return m.recorder
}

// CheckOrderExistence mocks base method.
func (m *MockOrderUseCase) CheckOrderExistence(ctx context.Context, orderNumber string, userID uint) (bool, uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckOrderExistence", ctx, orderNumber, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(uint)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CheckOrderExistence indicates an expected call of CheckOrderExistence.
func (mr *MockOrderUseCaseMockRecorder) CheckOrderExistence(ctx, orderNumber, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckOrderExistence", reflect.TypeOf((*MockOrderUseCase)(nil).CheckOrderExistence), ctx, orderNumber, userID)
}

// GetOrderByNumber mocks base method.
func (m *MockOrderUseCase) GetOrderByNumber(ctx context.Context, orderNumber string) (*entity.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderByNumber", ctx, orderNumber)
	ret0, _ := ret[0].(*entity.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrderByNumber indicates an expected call of GetOrderByNumber.
func (mr *MockOrderUseCaseMockRecorder) GetOrderByNumber(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderByNumber", reflect.TypeOf((*MockOrderUseCase)(nil).GetOrderByNumber), ctx, orderNumber)
}

// GetUserOrders mocks base method.
func (m *MockOrderUseCase) GetUserOrders(ctx context.Context, userID uint) ([]entity.OrderResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserOrders", ctx, userID)
	ret0, _ := ret[0].([]entity.OrderResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserOrders indicates an expected call of GetUserOrders.
func (mr *MockOrderUseCaseMockRecorder) GetUserOrders(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserOrders", reflect.TypeOf((*MockOrderUseCase)(nil).GetUserOrders), ctx, userID)
}

// SetOrders mocks base method.
func (m *MockOrderUseCase) SetOrders(ctx context.Context, userID uint, order entity.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOrders", ctx, userID, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOrders indicates an expected call of SetOrders.
func (mr *MockOrderUseCaseMockRecorder) SetOrders(ctx, userID, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOrders", reflect.TypeOf((*MockOrderUseCase)(nil).SetOrders), ctx, userID, order)
}

// ValidateOrder mocks base method.
func (m *MockOrderUseCase) ValidateOrder(order entity.Order, userID uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateOrder", order, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateOrder indicates an expected call of ValidateOrder.
func (mr *MockOrderUseCaseMockRecorder) ValidateOrder(order, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateOrder", reflect.TypeOf((*MockOrderUseCase)(nil).ValidateOrder), order, userID)
}

// MockBalanceUseCase is a mock of BalanceUseCase interface.
type MockBalanceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceUseCaseMockRecorder
}

// MockBalanceUseCaseMockRecorder is the mock recorder for MockBalanceUseCase.
type MockBalanceUseCaseMockRecorder struct {
	mock *MockBalanceUseCase
}

// NewMockBalanceUseCase creates a new mock instance.
func NewMockBalanceUseCase(ctrl *gomock.Controller) *MockBalanceUseCase {
	mock := &MockBalanceUseCase{ctrl: ctrl}
	mock.recorder = &MockBalanceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceUseCase) EXPECT() *MockBalanceUseCaseMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockBalanceUseCase) BeginTx(ctx context.Context) (v5.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(v5.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockBalanceUseCaseMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockBalanceUseCase)(nil).BeginTx), ctx)
}

// CreateWithdrawalTx mocks base method.
func (m *MockBalanceUseCase) CreateWithdrawalTx(ctx context.Context, withdrawal entity.Withdrawal, order *entity.OrderResponse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWithdrawalTx", ctx, withdrawal, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWithdrawalTx indicates an expected call of CreateWithdrawalTx.
func (mr *MockBalanceUseCaseMockRecorder) CreateWithdrawalTx(ctx, withdrawal, order interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWithdrawalTx", reflect.TypeOf((*MockBalanceUseCase)(nil).CreateWithdrawalTx), ctx, withdrawal, order)
}

// GetBalance mocks base method.
func (m *MockBalanceUseCase) GetBalance(ctx context.Context, userID string) (*entity.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, userID)
	ret0, _ := ret[0].(*entity.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockBalanceUseCaseMockRecorder) GetBalance(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockBalanceUseCase)(nil).GetBalance), ctx, userID)
}

// GetBalanceTx mocks base method.
func (m *MockBalanceUseCase) GetBalanceTx(ctx context.Context, tx v5.Tx, userID uint) (*entity.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceTx", ctx, tx, userID)
	ret0, _ := ret[0].(*entity.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceTx indicates an expected call of GetBalanceTx.
func (mr *MockBalanceUseCaseMockRecorder) GetBalanceTx(ctx, tx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceTx", reflect.TypeOf((*MockBalanceUseCase)(nil).GetBalanceTx), ctx, tx, userID)
}

// GetUserByLogin mocks base method.
func (m *MockBalanceUseCase) GetUserByLogin(ctx context.Context, u entity.User) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", ctx, u)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockBalanceUseCaseMockRecorder) GetUserByLogin(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockBalanceUseCase)(nil).GetUserByLogin), ctx, u)
}

// GetWithdrawals mocks base method.
func (m *MockBalanceUseCase) GetWithdrawals(ctx context.Context, userID uint) ([]entity.Withdrawal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawals", ctx, userID)
	ret0, _ := ret[0].([]entity.Withdrawal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawals indicates an expected call of GetWithdrawals.
func (mr *MockBalanceUseCaseMockRecorder) GetWithdrawals(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawals", reflect.TypeOf((*MockBalanceUseCase)(nil).GetWithdrawals), ctx, userID)
}

// UpdateBalanceTx mocks base method.
func (m *MockBalanceUseCase) UpdateBalanceTx(ctx context.Context, tx v5.Tx, userID uint, amount float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBalanceTx", ctx, tx, userID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBalanceTx indicates an expected call of UpdateBalanceTx.
func (mr *MockBalanceUseCaseMockRecorder) UpdateBalanceTx(ctx, tx, userID, amount interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBalanceTx", reflect.TypeOf((*MockBalanceUseCase)(nil).UpdateBalanceTx), ctx, tx, userID, amount)
}

// MockAuthUseCase is a mock of AuthUseCase interface.
type MockAuthUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseMockRecorder
}

// MockAuthUseCaseMockRecorder is the mock recorder for MockAuthUseCase.
type MockAuthUseCaseMockRecorder struct {
	mock *MockAuthUseCase
}

// NewMockAuthUseCase creates a new mock instance.
func NewMockAuthUseCase(ctrl *gomock.Controller) *MockAuthUseCase {
	mock := &MockAuthUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCase) EXPECT() *MockAuthUseCaseMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockAuthUseCase) CreateToken(ctx context.Context, u *entity.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAuthUseCaseMockRecorder) CreateToken(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockAuthUseCase)(nil).CreateToken), ctx, u)
}

// GetUserByEmail mocks base method.
func (m *MockAuthUseCase) GetUserByEmail(ctx context.Context, u entity.User) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, u)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockAuthUseCaseMockRecorder) GetUserByEmail(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockAuthUseCase)(nil).GetUserByEmail), ctx, u)
}

// GetUsers mocks base method.
func (m *MockAuthUseCase) GetUsers(arg0 context.Context) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsers", arg0)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsers indicates an expected call of GetUsers.
func (mr *MockAuthUseCaseMockRecorder) GetUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsers", reflect.TypeOf((*MockAuthUseCase)(nil).GetUsers), arg0)
}

// RegisterUser mocks base method.
func (m *MockAuthUseCase) RegisterUser(ctx context.Context, u entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockAuthUseCaseMockRecorder) RegisterUser(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockAuthUseCase)(nil).RegisterUser), ctx, u)
}

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// ExistOrderAccrual mocks base method.
func (m *MockRepository) ExistOrderAccrual(ctx context.Context, orderNumber string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistOrderAccrual", ctx, orderNumber)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistOrderAccrual indicates an expected call of ExistOrderAccrual.
func (mr *MockRepositoryMockRecorder) ExistOrderAccrual(ctx, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistOrderAccrual", reflect.TypeOf((*MockRepository)(nil).ExistOrderAccrual), ctx, orderNumber)
}

// GetUnprocessedOrders mocks base method.
func (m *MockRepository) GetUnprocessedOrders(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnprocessedOrders", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnprocessedOrders indicates an expected call of GetUnprocessedOrders.
func (mr *MockRepositoryMockRecorder) GetUnprocessedOrders(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnprocessedOrders", reflect.TypeOf((*MockRepository)(nil).GetUnprocessedOrders), ctx)
}

// SaveAccrual mocks base method.
func (m *MockRepository) SaveAccrual(ctx context.Context, orderNumber, status string, accrual float32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAccrual", ctx, orderNumber, status, accrual)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAccrual indicates an expected call of SaveAccrual.
func (mr *MockRepositoryMockRecorder) SaveAccrual(ctx, orderNumber, status, accrual interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAccrual", reflect.TypeOf((*MockRepository)(nil).SaveAccrual), ctx, orderNumber, status, accrual)
}

// MockPgxPool is a mock of PgxPool interface.
type MockPgxPool struct {
	ctrl     *gomock.Controller
	recorder *MockPgxPoolMockRecorder
}

// MockPgxPoolMockRecorder is the mock recorder for MockPgxPool.
type MockPgxPoolMockRecorder struct {
	mock *MockPgxPool
}

// NewMockPgxPool creates a new mock instance.
func NewMockPgxPool(ctrl *gomock.Controller) *MockPgxPool {
	mock := &MockPgxPool{ctrl: ctrl}
	mock.recorder = &MockPgxPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPgxPool) EXPECT() *MockPgxPoolMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPgxPool) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockPgxPoolMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPgxPool)(nil).Close))
}

// Exec mocks base method.
func (m *MockPgxPool) Exec(ctx context.Context, sql string, arguments ...interface{}) (pgconn.CommandTag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sql}
	for _, a := range arguments {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Exec", varargs...)
	ret0, _ := ret[0].(pgconn.CommandTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exec indicates an expected call of Exec.
func (mr *MockPgxPoolMockRecorder) Exec(ctx, sql interface{}, arguments ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sql}, arguments...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec", reflect.TypeOf((*MockPgxPool)(nil).Exec), varargs...)
}

// Query mocks base method.
func (m *MockPgxPool) Query(ctx context.Context, sql string, args ...interface{}) (v5.Rows, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(v5.Rows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockPgxPoolMockRecorder) Query(ctx, sql interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockPgxPool)(nil).Query), varargs...)
}

// QueryRow mocks base method.
func (m *MockPgxPool) QueryRow(ctx context.Context, sql string, args ...interface{}) v5.Row {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, sql}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "QueryRow", varargs...)
	ret0, _ := ret[0].(v5.Row)
	return ret0
}

// QueryRow indicates an expected call of QueryRow.
func (mr *MockPgxPoolMockRecorder) QueryRow(ctx, sql interface{}, args ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, sql}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryRow", reflect.TypeOf((*MockPgxPool)(nil).QueryRow), varargs...)
}

// MockPostgres is a mock of Postgres interface.
type MockPostgres struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresMockRecorder
}

// MockPostgresMockRecorder is the mock recorder for MockPostgres.
type MockPostgresMockRecorder struct {
	mock *MockPostgres
}

// NewMockPostgres creates a new mock instance.
func NewMockPostgres(ctrl *gomock.Controller) *MockPostgres {
	mock := &MockPostgres{ctrl: ctrl}
	mock.recorder = &MockPostgresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgres) EXPECT() *MockPostgresMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPostgres) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockPostgresMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPostgres)(nil).Close))
}

// GetPool mocks base method.
func (m *MockPostgres) GetPool() PgxPool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPool")
	ret0, _ := ret[0].(PgxPool)
	return ret0
}

// GetPool indicates an expected call of GetPool.
func (mr *MockPostgresMockRecorder) GetPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPool", reflect.TypeOf((*MockPostgres)(nil).GetPool))
}

// MockRows is a mock of Rows interface.
type MockRows struct {
	ctrl     *gomock.Controller
	recorder *MockRowsMockRecorder
}

// MockRowsMockRecorder is the mock recorder for MockRows.
type MockRowsMockRecorder struct {
	mock *MockRows
}

// NewMockRows creates a new mock instance.
func NewMockRows(ctrl *gomock.Controller) *MockRows {
	mock := &MockRows{ctrl: ctrl}
	mock.recorder = &MockRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRows) EXPECT() *MockRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockRows) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockRows)(nil).Close))
}

// Next mocks base method.
func (m *MockRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockRows)(nil).Next))
}

// Scan mocks base method.
func (m *MockRows) Scan(dest ...interface{}) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockRowsMockRecorder) Scan(dest ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockRows)(nil).Scan), dest...)
}
